### ISSUE TITLE
phpinfo plugin trigger false positives

### ISSUE THREAD

**Issue by mtskg** [andresriancho/w3af#14956]
I have found that the phpinfo plugin often trigger false positives, seems like the php_version validation is not stopping non phpinfo URLs from being accepted as phpinfo files?

**Comment by andresriancho** [comment]
An example where php_version trigger false positives was sent over email by @mtskg:

Can it be that php_version validation is not working/run as expected? https://github.com/andresriancho/w3af/blob/master/w3af/plugins/crawl/phpinfo.py#L123

URLs where this problem is triggered:
 * http://xyz/test.php
 * http://xyz/INSTALL.php
 * http://xyz/x.php
 * http://xyz/install.php

Looks strange too, since the HTTP response code for these example sites is also 404 (like in https://github.com/andresriancho/w3af/issues/14955).
