### ISSUE TITLE
plugin development help

### ISSUE THREAD

**Issue by RoundJ** [andresriancho/w3af#16151]
Hi, I have used this great tool for a while, but cannot find any tutorial or documentation on how to write a new plugin. I have an urgent need for that. Would you give me some recommendation, it will be appreciated~

**Comment by andresriancho** [comment]
Thanks for wanting to contribute, take a look at:

https://github.com/andresriancho/w3af/wiki/First-steps-as-a-contributor
https://github.com/andresriancho/w3af/wiki/Contributing-101
https://github.com/andresriancho/w3af/wiki/Developer's-Guide

And you can ask any questions here.

What feature do you want to add?

**Comment by RoundJ** [comment]
Thanks for response. I just want to write audit plugins for new vulnerabilities like business logic.

**Comment by andresriancho** [comment]
In order for any scanner to identify business logic flaws it first needs to understand the rules that govern a specific business (in an online banking, the user shouldn't be able to transfer negative funds). Then, it needs to understand how those rules are "exposed" by the application (the user's balance is in parameter X) and finally you can test for those using HTTP requests.

I haven't seen any tool do this for generic web applications. When I saw this it was done using unittests/integration tests for the web application itself.

What do you have in mind?

**Comment by RoundJ** [comment]
I absolutely agree with you on how to identify business logic flaws.
I read some papers listed as follows, on how to discovery parameter pollution vulnerabilities, xss and sql injection automatically, and want to do further work. 

Balduzzi M, Gimenez C T, Balzarotti D, et al. Automated Discovery of Parameter Pollution Vulnerabilities in Web Applications[C]//NDSS. 2011.
Deepa G, Thilagam P S, Khan F A, et al. Black-box detection of XQuery injection and parameter tampering vulnerabilities in web applications[J]. International Journal of Information Security, 2017: 1-16.

I don't have a big picture for now without making early experiments. I should find more evidence.

**Comment by andresriancho** [comment]
Take a look at https://github.com/andresriancho/w3af/blob/master/w3af/plugins/audit/sqli.py , it is pretty easy to read.

The most interesting part is here: https://github.com/andresriancho/w3af/blob/master/w3af/plugins/audit/sqli.py#L178 where the `create_mutants` method receives a `freq` (fuzzable request, an HTTP request) and modifies each parameter so that it contains `SQLI_STRINGS`. That returns a list of mutants that are then sent in the line below.

Then https://github.com/andresriancho/w3af/blob/master/w3af/plugins/audit/sqli.py#L184 tries to find SQL injection errors.

**Comment by RoundJ** [comment]
It does work~
