### ISSUE TITLE
Cannot run w3af api with config file

### ISSUE THREAD

**Issue by falconz** [andresriancho/w3af#17163]
I tried to run w3af with config file but I got error:

> w3af_api: error: argument -c: can't open '/root/w3af/extras/docker/scripts/config.yml': [Errno 2] No such file or directory: '/root/w3af/extras/docker/scripts/config.yml'

![image](https://user-images.githubusercontent.com/9218490/43635591-be811e0a-9739-11e8-898e-2303c8852d23.png)

**Comment by andresriancho** [comment]
The problem seems to be that the w3af process inside docker is not seeing the configuration file. This is because there are two different file systems in play.

You'll have to copy the configuration file to a shared directory, please see:
http://docs.w3af.org/en/latest/docker.html#sharing-data-with-the-container
