### ISSUE TITLE
remote execution when loading history data

### ISSUE THREAD

**Issue by nanshihui** [andresriancho/w3af#17807]
### Version Information
  Python version: 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]
  Platform: Ubuntu 16.04 xenial
  GTK version: 2.24.30
  PyGTK version: 2.24.0
  w3af version:
    w3af - Web Application Attack and Audit Framework
    Version: 2019.1.2
    Revision: 219d9df7b0 - 16 3月 2019 14:15
    Branch: master
    Local changes: Yes
    Author: Andres Riancho and the w3af team.
### Influences
 attacker can overwrite  w3af temporary files which can lead to remote command execution or use it as backdoor. 
### Detail

copy the  follow file to your w3af cache path  '~/.w3af/urlhistory.pkl'
https://github.com/nanshihui/exps/blob/master/urlhistory.pkl
then run w3af_gui
you will find that  there is a request to 10.8.37.92:8888

![Jietu20190424-160949](https://user-images.githubusercontent.com/6913510/56643158-a5e1f300-66ab-11e9-8f87-dc265980fb9c.jpg)
![Jietu20190424-161028](https://user-images.githubusercontent.com/6913510/56643177-af6b5b00-66ab-11e9-96c8-ed438776e9a1.jpg)

**Comment by andresriancho** [comment]
First of all, thanks for your detailed vulnerability report. I confirm that this works and could, in some very limited scenarios, be used by an attacker.

There are several areas of w3af code which use pickle to serialize and unserialize data from disk:

```
find . -type f -name '*py' | xargs egrep -e '(import cPickle|import pickle)' | grep -v '/test_' | grep -v 'db/sqlmap/' | grep -v 'show-test-ids'
./w3af/core/ui/gui/history.py:import cPickle
./w3af/core/data/misc/cpickle_dumps.py:import cPickle
./w3af/core/data/kb/knowledge_base.py:import cPickle
./w3af/core/data/parsers/ipc/serialization.py:import cPickle
./w3af/core/data/db/tests/serialization_perf.py:    import cPickle
./w3af/core/data/db/disk_list.py:import cPickle
./w3af/core/data/db/disk_dict.py:import cPickle
./w3af/core/controllers/profiling/pytracemalloc.py:import cPickle
./w3af/core/controllers/threads/pool276.py:import cPickle
./w3af/plugins/audit/deserialization/python/generator.py:import cPickle
```

The easiest vector to exploit this issue is the one you mention, because all of the other files are either temporary or are strings stored inside a DB.

The risk associated with this vulnerability is **really low**. An attacker needs to be able to write files to the victim's home directory to perform the attack. If an attacker can do that, I guess there are other thousand more effective things that could be done to persist in the system.

Anyways, I'll fix the reported instance because it is easy enough and provides the more direct attack path.

**Comment by andresriancho** [comment]
Could you please confirm the fix at https://github.com/andresriancho/w3af/commit/190733835cddf1e14d1f12c4711de73d1379c0e3 ?

**Comment by nanshihui** [comment]
it worked

**Comment by andresriancho** [comment]
OK! Thanks for your help!
